version: '3.8'

services:
  java-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/academy
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL-AUTO: update  # Adicionei esta linha importante
      SPRING_DATASOURCE_HIKARI_CONNECTION-TIMEOUT: 30000  # Timeout aumentado
    networks:
      - app-network
    depends_on:
      postgres-db:
        condition: service_healthy  # Modificação crucial

  postgres-db:
    image: postgres:15-alpine  # Versão mais leve
    container_name: postgres-db
    environment:
      POSTGRES_DB: academy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:  # Adicionei healthcheck
      test: ["CMD-SHELL", "pg_isready -U postgres -d academy"]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: